### PR TITLE
Fix NNP (a.k.a. QMML)

### PR DESCRIPTION
**Pull request by raimis**
Dependency of https://github.com/Acellera/htmd/pull/816
~~Depend on #23~~

### CODE REVIEW

**Comment by raimis** [comment]
@stefdoerr can you review, please.

**Comment by raimis** [comment]
@stefdoerr and this one?

**Comment by stefdoerr** [comment]
Why did so many files change when adding NNPs?

**Comment by raimis** [comment]
Renaming: `parameters/GAFF2/B3LYP-cc-pVDZ-vacuum/` --> `parameters/`

**Comment by stefdoerr** [comment]
Oh so it will break all other PRs. Wait maybe to see if I can fix/merge the scipy optimizer first.

**Comment by raimis** [comment]
Equally scipy optimizer changes will brake this...

**Comment by j3mdamas** [comment]
@stefdoerr I agree and I understand the frustration. Let's try to find a solution.

**Pull request merged**
